version: 0.0
os: linux
files:
  - source: / # 인스턴스에 복사할 S3 파일의 경로입니다. / 로 설정하면S3_BUCKET_NAME/PROJECT_NAME/GITHUB_SHA.zip을 가져옵니다.
    destination: /home/ubuntu/onetomany # S3에서 가져온 파일을 저장할 위치입니다.
    overwrite: yes # 덮어쓰기를 허용하는 옵션입니다.

# files에서 가져온 파일들에게 권한을 어떻게 적용해야하는지 지정하는 곳입니다.
permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:

  #  Install:
  #    - runas: ubuntu
  #      commands:
  #        - chmod +x /home/ubuntu/deploy/scripts/before-install.sh
  #        - chmod +x /home/ubuntu/deploy/scripts/after-install.sh

  #  BeforeInstall:
  #    - location: scripts/before-install.sh
  #      runas: ubuntu

  AfterInstall:
    - location: scripts/after-install.sh
      runas: ubuntu

  ValidateService:
    - location: scripts/validate-service.sh
      runas: ubuntu
