name: Build and Upload to S3

on:
  push:
    branches:
      - main

jobs:

  build:
    environment: DEPLOY
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create secret.properties
        run: |
          echo "${{ secrets.ENV }}" > src/main/resources/secret.properties


      - name: Build JAR
        run: |
          ./gradlew clean build -x test
