name: Build and Upload to S3

on:
  push:
    branches:
      - main

jobs:

  build:
    environment: DEPLOY
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create secret.properties
        run: |
          echo "${{ secrets.ENV }}" > src/main/resources/secret.properties

      - name: Create secret-test.properties
        run: |
          echo "${{ secrets.TEST_ENV }}" > src/main/resources/secret-test.properties

      - name: Build JAR
        run: |
          ./gradlew clean build

      - name: Make a zip file
        run: |
          zip $GITHUB_SHA.zip build/libs/onetomany-0.0.1-SNAPSHOT.jar appspec.yml -r scripts
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp $GITHUB_SHA.zip s3://onetomany-server/onetomany/$GITHUB_SHA.zip

      - name: Request Deployment
        run: aws deploy create-deployment
          --application-name onetomany-code-deploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name onetomany-code-deploy
          --s3-location bucket=onetomany-server,bundleType=zip,key=deploy/$GITHUB_SHA.zip